name: autobird-sweep
method: random
metric:
  name: val/loss
  goal: minimize
# Hydra compatibility, makes sure that different params er tested
command:
  - ${env}
  - ${interpreter}
  - -m
  - call_of_birds_autobird.train
  - ${args_no_boolean_flags}
parameters:
  # Hydra override paths (match your cfg structure)
  train.hyperparams.hyperparameters.lr:
    distribution: log_uniform_values
    min: 1e-5
    max: 3e-3
  train.hyperparams.hyperparameters.batch_size:
    values: [16, 32, 64]
  train.hyperparams.hyperparameters.epochs:
    values: [1, 2, 3]
run_cap: 3
