# config_cpu.yaml
workerPoolSpecs:
    machineSpec:
        machineType: n1-highmem-2
    replicaCount: 1
    containerSpec:
        imageUri: europe-west1-docker.pkg.dev/autobird-484409/autobird-container/train-image:latest
        env:
            - name: WANDB_MODE
              value: "disabled"