_wandb:
    value:
        cli_version: 0.24.0
        e:
            ec75lkcxcxicb6ikv58br1h03qnuuu3y:
                apple:
                    ecpuCores: 4
                    gpuCores: 10
                    memoryGb: 8
                    name: Apple M3
                    pcpuCores: 4
                    ramTotalBytes: "8589934592"
                    swapTotalBytes: "18253611008"
                cpu_count: 8
                cpu_count_logical: 8
                disk:
                    /:
                        total: "994662584320"
                        used: "251500212224"
                email: s224022@dtu.dk
                executable: /Users/mortenkleist/Documents/DTU/autobird/.venv/bin/python3
                git:
                    commit: f75e99fdce6193c353294980d1615090a0aefe32
                    remote: git@github.com:MLOpsGroup47/autobird.git
                host: MacBook-Pro-tilhrende-Morten-2.local
                memory:
                    total: "8589934592"
                os: macOS-15.1.1-arm64-arm-64bit
                program: -m call_of_birds_autobird.train
                python: CPython 3.12.12
                root: /Users/mortenkleist/Documents/DTU/autobird
                startedAt: "2026-01-22T11:59:22.111562Z"
                writerId: ec75lkcxcxicb6ikv58br1h03qnuuu3y
        m: []
        python_version: 3.12.12
        t:
            "1":
                - 1
                - 50
                - 105
            "2":
                - 1
                - 50
                - 105
            "3":
                - 13
                - 16
            "4": 3.12.12
            "5": 0.24.0
            "12": 0.24.0
            "13": darwin-arm64
data:
    value:
        clip_sec: 5
        pad_last: true
        seed: 4
        stride_sec: 2.5
        test_split: 0.1
        train_split: 0.8
paths:
    value:
        ckpt_dir: models/checkpoints
        eval_dir: reports/eval_metrics
        processed_dir: data/processed
        profile_dir: reports/torch_prof
        raw_dir: data/voice_of_birds
        reports_dir: reports
        root: .
        x_train: data/processed/train_x.pt
        x_val: data/processed/val_x.pt
        y_train: data/processed/train_y.pt
        y_val: data/processed/val_y.pt
preprocessing:
    value:
        clip_sec: 5
        fq_max: 8000
        fq_min: 20
        hop_length: 512
        min_mel_std: 0.1
        min_rms: 0.005
        min_samples: 50
        n_fft: 1024
        n_mels: 64
        sr: 16000
train:
    value:
        hp:
            amp: true
            batch_size: 32
            d_model: 64
            epochs: 3
            grad_clip: 1
            lr: 0.0003
            n_heads: 2
            n_layers: 1
            num_workers: 2
            pin_memory: false
            sample_min: 50
            shuffle_train: true
            shuffle_val: false
            use_wandb: true
        optim:
            _target_: torch.optim.Adam
            lr: 0.0003
            weight_decay: 0.0001
        prof:
            active: 3
            enabled: false
            profile_memory: true
            record_shapes: true
            repeat: 1
            wait: 1
            warmup: 1
            with_stack: false
        slr:
            _target_: torch.optim.lr_scheduler.StepLR
            gamma: 0.5
            step_size: 5
