# @package _global_

paths:
  root: .
  raw_dir: data/voice_of_birds
  processed_dir: data/processed
  reports_dir: reports/figures
  ckpt_dir: models/checkpoints
  x_train:: data/processed/x_train.pt
  y_train: data/processed/y_train.pt
  x_val: data/processed/x_val.pt
  y_val: data/processed(y_val.pt