# @package _global_

paths:
  root: .
  raw_dir: data/voice_of_birds
  processed_dir: data/processed
  reports_dir: reports
  eval_dir: reports/eval_metrics
  ckpt_dir: models/checkpoints
  profile_dir: reports/torch_prof
  out_dir: ${paths.processed_dir}/shards
  x_train: ${paths.processed_dir}/train_x.pt
  y_train: ${paths.processed_dir}/train_y.pt
  x_val: ${paths.processed_dir}/val_x.pt
  y_val: ${paths.processed_dir}/val_y.pt