# @package _global_

paths:
  root: .
  raw_dir: data/voice_of_birds
  processed_dir: data/processed
  reports_dir: reports/figures
  ckpt_dir: models/checkpoints
  profile_dir: reports/torch_prof
  x_train: data/processed/train_x.pt
  y_train: data/processed/train_y.pt
  x_val: data/processed/val_x.pt
  y_val: data/processed/val_y.pt