_wandb:
    value:
        cli_version: 0.24.0
        e:
            qbw5h7l9lp1l2dn7hsb8st4xhd245rpa:
                apple:
                    ecpuCores: 4
                    gpuCores: 16
                    memoryGb: 16
                    name: Apple M2 Pro
                    pcpuCores: 6
                    ramTotalBytes: "17179869184"
                    swapTotalBytes: "4294967296"
                args:
                    - train.hp.num_workers=0
                codePath: .venv/bin/train
                codePathLocal: .venv/bin/train
                cpu_count: 10
                cpu_count_logical: 10
                disk:
                    /:
                        total: "494384795648"
                        used: "466421055488"
                email: s214776@dtu.dk
                executable: /Users/holgermaxfloelyng/Desktop/BioMed/MSc_Biomed/SEM_3/project/mlops_project/.venv/bin/python3
                git:
                    commit: 4bf8a8e30cc20ad06a7577fc6e08c86c95f7443e
                    remote: https://github.com/MLOpsGroup47/autobird.git
                host: mac.students.clients.local
                memory:
                    total: "17179869184"
                os: macOS-26.1-arm64-arm-64bit
                program: /Users/holgermaxfloelyng/Desktop/BioMed/MSc_Biomed/SEM_3/project/mlops_project/.venv/bin/train
                python: CPython 3.12.12
                root: /Users/holgermaxfloelyng/Desktop/BioMed/MSc_Biomed/SEM_3/project/mlops_project
                startedAt: "2026-01-23T09:44:54.957466Z"
                writerId: qbw5h7l9lp1l2dn7hsb8st4xhd245rpa
        m: []
        python_version: 3.12.12
        t:
            "1":
                - 1
                - 50
                - 105
            "2":
                - 1
                - 50
                - 105
            "3":
                - 2
                - 13
                - 16
            "4": 3.12.12
            "5": 0.24.0
            "12": 0.24.0
            "13": darwin-arm64
data:
    value:
        clip_sec: 5
        pad_last: true
        seed: 4
        stride_sec: 2.5
        test_split: 0.1
        train_split: 0.8
paths:
    value:
        ckpt_dir: models/checkpoints
        eval_dir: reports/eval_metrics
        out_dir: data/processed/shards
        processed_dir: data/processed
        profile_dir: reports/torch_prof
        raw_dir: data/voice_of_birds
        reports_dir: reports
        root: .
        x_train: data/processed/train_x.pt
        x_val: data/processed/val_x.pt
        y_train: data/processed/train_y.pt
        y_val: data/processed/val_y.pt
preprocessing:
    value:
        clip_sec: 5
        fq_max: 8000
        fq_min: 20
        hop_length: 512
        min_mel_std: 0.1
        min_rms: 0.005
        min_samples: 50
        n_fft: 1024
        n_mels: 64
        sr: 16000
runtime:
    value:
        local_rank: 0
        rank: 0
        world_size: 1
train:
    value:
        hp:
            amp: true
            batch_size: 32
            d_model: 64
            epochs: 3
            grad_clip: 1
            lr: 0.0003
            n_heads: 2
            n_layers: 1
            num_workers: 0
            pin_memory: false
            shuffle_train: true
            shuffle_val: false
            use_wandb: true
            use_ws: false
        optim:
            _target_: torch.optim.Adam
            lr: 0.0003
            weight_decay: 0.0001
        prof:
            active: 3
            enabled: false
            profile_memory: true
            record_shapes: true
            repeat: 1
            wait: 1
            warmup: 1
            with_stack: false
        slr:
            _target_: torch.optim.lr_scheduler.StepLR
            gamma: 0.5
            step_size: 5
