# @package train.hp

epochs: 3
lr: 0.0003
batch_size: 32
d_model: 64
n_heads: 2
n_layers: 1
pin_memory: false
shuffle_train: true
shuffle_val: false
num_workers: 2
amp: true
specaug: false
grad_clip: 1.0
use_wandb: true
use_ws: false


