_wandb:
    value:
        cli_version: 0.24.0
        e:
            iyb7pdgqkica4law4k7vlk38hkesx98u:
                codePath: .venv/bin/train
                codePathLocal: .venv/bin/train
                cpu_count: 2
                cpu_count_logical: 4
                disk:
                    /:
                        total: "250790436864"
                        used: "209593524224"
                email: weloveaus@gmail.com
                executable: /Users/asmustangdalsgaard/Desktop/DTU_Master/mlops_project/autobird/.venv/bin/python3
                git:
                    commit: ad4f2444e81f82e333f3b7537b1d822706761ab8
                    remote: https://github.com/MLOpsGroup47/autobird.git
                host: Asmuss-MacBook-Pro.local
                memory:
                    total: "8589934592"
                os: macOS-12.7.4-x86_64-i386-64bit
                program: /Users/asmustangdalsgaard/Desktop/DTU_Master/mlops_project/autobird/.venv/bin/train
                python: CPython 3.12.11
                root: /Users/asmustangdalsgaard/Desktop/DTU_Master/mlops_project/autobird
                startedAt: "2026-01-17T14:34:38.820467Z"
                writerId: iyb7pdgqkica4law4k7vlk38hkesx98u
        m: []
        python_version: 3.12.11
        t:
            "1":
                - 1
                - 50
                - 105
            "2":
                - 1
                - 50
                - 105
            "3":
                - 13
                - 16
            "4": 3.12.11
            "5": 0.24.0
            "12": 0.24.0
            "13": darwin-x86_64
data:
    value:
        clip_sec: 5
        pad_last: true
        seed: 4
        stride_sec: 2.5
        train_split: 0.8
paths:
    value:
        ckpt_dir: models/checkpoints
        processed_dir: data/processed
        raw_dir: data/voice_of_birds
        reports_dir: reports/figures
        root: .
        x_train: data/processed/train_x.pt
        x_val: data/processed/val_x.pt
        y_train: data/processed/train_y.pt
        y_val: data/processed/val_y.pt
preprocessing:
    value:
        clip_sec: 5
        fq_max: 8000
        fq_min: 20
        hop_length: 512
        min_mel_std: 0.1
        min_rms: 0.005
        min_samples: 20
        n_fft: 1024
        n_mels: 64
        sr: 16000
train:
    value:
        hyperparams:
            hyperparameters:
                amp: true
                batch_size: 32
                d_model: 64
                epochs: 3
                grad_clip: 1
                lr: 0.0003
                n_heads: 2
                n_layers: 1
                num_workers: 2
                pin_memory: false
                sample_min: 50
                shuffle_train: true
                shuffle_val: false
                use_wandb: true
        optimizer:
            Optimizer:
                lr: 0.0003
                type: torch.optim.Adam
                weight_decay: 0.0001
        scheduler:
            Scheduler:
                gamma: 0.5
                step_size: 5
                type: torch.optim.lr_scheduler.StepLR
