_wandb:
    value:
        cli_version: 0.24.0
        e:
            d4viitk5fc47ug9124onwu9795nsjff3:
                args:
                    - train.hp.epochs=1
                cpu_count: 10
                cpu_count_logical: 12
                disk:
                    /:
                        total: "509722226688"
                        used: "478018826240"
                email: s224031@dtu.dk
                executable: C:\Users\gusta\UniGit\autobird\.venv\Scripts\python.exe
                git:
                    commit: ddb0597e7babd1af91df3a68bd852215d6d86f11
                    remote: https://github.com/MLOpsGroup47/autobird.git
                host: GustavLaptop
                memory:
                    total: "8274370560"
                os: Windows-11-10.0.26100-SP0
                program: -m __main__
                python: CPython 3.12.1
                root: C:\Users\gusta\UniGit\autobird
                startedAt: "2026-01-23T09:07:41.593518Z"
                writerId: d4viitk5fc47ug9124onwu9795nsjff3
        m: []
        python_version: 3.12.1
        t:
            "1":
                - 1
                - 50
                - 105
            "2":
                - 1
                - 50
                - 105
            "3":
                - 2
                - 13
                - 16
            "4": 3.12.1
            "5": 0.24.0
            "8":
                - 3
            "12": 0.24.0
            "13": windows-amd64
data:
    value:
        clip_sec: 5
        pad_last: true
        seed: 4
        stride_sec: 2.5
        test_split: 0.1
        train_split: 0.8
paths:
    value:
        ckpt_dir: models/checkpoints
        eval_dir: reports/eval_metrics
        out_dir: data/processed/shards
        processed_dir: data/processed
        profile_dir: reports/torch_prof
        raw_dir: data/voice_of_birds
        reports_dir: reports
        root: .
        x_train: data/processed/train_x.pt
        x_val: data/processed/val_x.pt
        y_train: data/processed/train_y.pt
        y_val: data/processed/val_y.pt
preprocessing:
    value:
        clip_sec: 5
        fq_max: 8000
        fq_min: 20
        hop_length: 512
        min_mel_std: 0.1
        min_rms: 0.005
        min_samples: 50
        n_fft: 1024
        n_mels: 64
        sr: 16000
runtime:
    value:
        local_rank: 0
        rank: 0
        world_size: 1
train:
    value:
        hp:
            amp: true
            batch_size: 32
            d_model: 64
            epochs: 1
            grad_clip: 1
            lr: 0.0003
            n_heads: 2
            n_layers: 1
            num_workers: 2
            pin_memory: false
            shuffle_train: true
            shuffle_val: false
            use_wandb: true
            use_ws: false
        optim:
            _target_: torch.optim.Adam
            lr: 0.0003
            weight_decay: 0.0001
        prof:
            active: 3
            enabled: false
            profile_memory: true
            record_shapes: true
            repeat: 1
            wait: 1
            warmup: 1
            with_stack: false
        slr:
            _target_: torch.optim.lr_scheduler.StepLR
            gamma: 0.5
            step_size: 5
