defaults: 
  - pathing: path_config
  - data: data_config
  - hyperparams: hyperparam
  - optimizer: adam
  - prof: profiler_config
  - scheduler: step
  - ddp: runtime
  - _self_

hydra:
  job:
    chdir: false